# Generated by Django 6.0.7 on 2026-07-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('full_name', models.CharField(blank=True, max_length=512, verbose_name='Полное наименование')),
                ('kind', models.CharField(choices=[('legal', 'Юридическое лицо'), ('entrepreneur', 'Индивидуальный предприниматель'), ('person', 'Физическое лицо')], default='legal', max_length=16, verbose_name='Форма')),
                ('partner_type', models.CharField(choices=[('customer', 'Покупатель'), ('supplier', 'Поставщик'), ('both', 'Покупатель и поставщик')], default='customer', max_length=16, verbose_name='Тип')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН/ОГРНИП')),
                ('legal_address', models.CharField(blank=True, max_length=512, verbose_name='Юридический адрес')),
                ('actual_address', models.CharField(blank=True, max_length=512, verbose_name='Фактический адрес')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('director_name', models.CharField(blank=True, max_length=255, verbose_name='Руководитель (ФИО, для документов)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='Номер')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Организация')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='partners.counterparty')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('account', models.CharField(max_length=20, verbose_name='Расчётный счёт')),
                ('corr_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт')),
                ('is_default', models.BooleanField(default=False, verbose_name='Основной')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='partners.counterparty')),
            ],
            options={
                'verbose_name': 'Банковский счёт',
                'verbose_name_plural': 'Банковские счета',
            },
        ),
    ]
