# Generated by Django 6.0.7 on 2026-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='okpo',
            field=models.CharField(blank=True, max_length=14, verbose_name='ОКПО'),
        ),
    ]
