# Generated by Django 6.0.7 on 2026-09-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_contactperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('kind', models.CharField(choices=[('supply', 'Договор поставки'), ('sale', 'Договор купли-продажи'), ('service', 'Договор оказания услуг'), ('other', 'Другое')], default='other', max_length=16, verbose_name='Вид договора')),
                ('body', models.TextField(verbose_name='Текст договора')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='Типовой (из поставки)')),
            ],
            options={
                'verbose_name': 'Шаблон договора',
                'verbose_name_plural': 'Шаблоны договоров',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма договора'),
        ),
        migrations.AddField(
            model_name='contract',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='Автопролонгация'),
        ),
        migrations.AddField(
            model_name='contract',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_perpetual',
            field=models.BooleanField(default=False, verbose_name='Бессрочный'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_delay_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Отсрочка платежа, дней'),
        ),
        migrations.AddField(
            model_name='contract',
            name='prepayment_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Предоплата, %'),
        ),
        migrations.AddField(
            model_name='contract',
            name='scan',
            field=models.FileField(blank=True, upload_to='contracts/', verbose_name='Скан подписанного'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subject',
            field=models.TextField(blank=True, verbose_name='Предмет договора'),
        ),
        migrations.AddField(
            model_name='contract',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Действует с'),
        ),
        migrations.AddField(
            model_name='contract',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='Действует по'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='partners.contracttemplate', verbose_name='Шаблон договора'),
        ),
    ]
