# Generated by Django 6.0.7 on 2026-09-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_contracttemplate_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место подписания'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Преамбула (шапка договора)'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='outro',
            field=models.TextField(blank=True, verbose_name='Реквизиты и подписи'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок документа'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст договора (устар.)'),
        ),
        migrations.CreateModel(
            name='ContractQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=255, verbose_name='Раздел договора')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('help_text', models.CharField(blank=True, max_length=512, verbose_name='Подсказка')),
                ('allow_none', models.BooleanField(default=True, verbose_name='Разрешить «Пункт не предусмотрен»')),
                ('allow_custom', models.BooleanField(default=True, verbose_name='Разрешить «Свой вариант»')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='partners.contracttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Вопрос договора',
                'verbose_name_plural': 'Вопросы договора',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('label', models.CharField(max_length=255, verbose_name='Вариант (что видит пользователь)')),
                ('body', models.TextField(verbose_name='Текст в договор')),
                ('is_default', models.BooleanField(default=False, verbose_name='Выбран по умолчанию')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='partners.contractquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант формулировки',
                'verbose_name_plural': 'Варианты формулировок',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.TextField(blank=True, verbose_name='Свой вариант')),
                ('is_skipped', models.BooleanField(default=False, verbose_name='Пункт не предусмотрен')),
                ('body_snapshot', models.TextField(blank=True, verbose_name='Текст пункта')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='partners.contract', verbose_name='Договор')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.contractoption', verbose_name='Вариант')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.contractquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ по договору',
                'verbose_name_plural': 'Ответы по договору',
                'ordering': ['question__order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('contract', 'question'), name='uniq_contract_question')],
            },
        ),
    ]
