# Generated by Django 6.0.7 on 2026-09-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_builtin_supply_constructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='claim_days',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Срок ответа на претензию, дней'),
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок поставки, дней'),
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=512, verbose_name='Место поставки'),
        ),
        migrations.AddField(
            model_name='contract',
            name='penalty_cap_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=5, null=True, verbose_name='Предельная неустойка, % от суммы'),
        ),
        migrations.AddField(
            model_name='contract',
            name='penalty_rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.1, max_digits=5, null=True, verbose_name='Неустойка, % в день'),
        ),
        migrations.AddField(
            model_name='contract',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Гарантия, месяцев'),
        ),
    ]
