# Generated by Django 6.0.7 on 2026-09-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_supply_constructor_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='goods_condition',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('used', 'Бывший в употреблении'), ('refurbished', 'Восстановленный'), ('display', 'Витринный образец'), ('defect', 'С недостатками (уценённый)')], max_length=16, verbose_name='Состояние товара'),
        ),
        migrations.AddField(
            model_name='contract',
            name='goods_details',
            field=models.TextField(blank=True, help_text='Марка, модель, серийный/заводской номер, год выпуска, наработка, комплектация', verbose_name='Сведения о товаре'),
        ),
    ]
