# Generated by Django 6.0.7 on 2026-09-08 15:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_supply_subject_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='penalty_rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.1'), max_digits=5, null=True, verbose_name='Неустойка, % в день'),
        ),
    ]
