# Generated by Django 6.0.7 on 2026-09-10 10:10

import apps.core.models
from django.db import migrations, models


def fill_time_from_created(apps, schema_editor):
    """Время уже существующих документов — момент их создания (местное время)."""
    from django.utils import timezone

    for name in ['Invoice', 'Shipment', 'CustomerReturn']:
        model = apps.get_model('sales', name)
        for doc in model.objects.exclude(created_at=None).only("pk", "created_at"):
            local = timezone.localtime(doc.created_at).time().replace(microsecond=0)
            model.objects.filter(pk=doc.pk).update(time=local)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_customerreturnline_discount_invoiceline_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerreturn',
            options={'ordering': ['-date', '-time', '-id'], 'verbose_name': 'Возврат покупателя', 'verbose_name_plural': 'Возвраты покупателей'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date', '-time', '-id'], 'verbose_name': 'Счёт покупателю', 'verbose_name_plural': 'Счета покупателям'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-date', '-time', '-id'], 'verbose_name': 'Отгрузка', 'verbose_name_plural': 'Отгрузки'},
        ),
        migrations.AddField(
            model_name='customerreturn',
            name='time',
            field=models.TimeField(default=apps.core.models.current_time, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='time',
            field=models.TimeField(default=apps.core.models.current_time, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='time',
            field=models.TimeField(default=apps.core.models.current_time, verbose_name='Время'),
        ),
        migrations.RunPython(fill_time_from_created, migrations.RunPython.noop),
    ]
