# Generated by Django 6.0.7 on 2026-09-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_customerreturn_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreturnline',
            name='serial_numbers',
            field=models.TextField(blank=True, help_text='По одному номеру в строке', verbose_name='Серийные номера'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='serial_numbers',
            field=models.TextField(blank=True, help_text='По одному номеру в строке', verbose_name='Серийные номера'),
        ),
        migrations.AddField(
            model_name='shipmentline',
            name='serial_numbers',
            field=models.TextField(blank=True, help_text='По одному номеру в строке', verbose_name='Серийные номера'),
        ),
    ]
