# Generated by Django 6.0.7 on 2026-07-22 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('partners', '0002_counterparty_okpo'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('kind', models.CharField(choices=[('cash', 'Касса'), ('bank', 'Расчётный счёт')], default='bank', max_length=8, verbose_name='Тип')),
                ('bank_account', models.CharField(blank=True, max_length=32, verbose_name='Номер счёта')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Начальный остаток')),
                ('is_default', models.BooleanField(default=False, verbose_name='Основной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Счёт/касса',
                'verbose_name_plural': 'Счета и кассы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('incoming', 'Входящий платёж'), ('outgoing', 'Исходящий платёж')], max_length=16, verbose_name='Вид')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='Номер')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('purpose', models.CharField(blank=True, max_length=512, verbose_name='Назначение платежа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён')], default='draft', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account', verbose_name='Счёт/касса')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='partners.counterparty', verbose_name='Контрагент')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.invoice', verbose_name='Счёт-основание')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
