# Generated by Django 6.0.7 on 2026-08-06 16:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_default_vat_rate'),
        ('finance', '0001_initial'),
        ('partners', '0002_counterparty_okpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='Номер')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Расчётный остаток')),
                ('actual_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Фактический остаток')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма корректировки')),
                ('comment', models.CharField(blank=True, max_length=512, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён')], default='draft', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='finance.account', verbose_name='Счёт/касса')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Корректировка остатка',
                'verbose_name_plural': 'Корректировки остатков',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SettlementCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='Номер')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('direction', models.CharField(choices=[('they_owe', 'Контрагент должен нам'), ('we_owe', 'Мы должны контрагенту')], default='they_owe', max_length=16, verbose_name='Направление')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=512, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён')], default='draft', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_corrections', to='partners.counterparty', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Корректировка взаиморасчётов',
                'verbose_name_plural': 'Корректировки взаиморасчётов',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
