# Generated by Django 6.0.7 on 2026-09-10 10:10

import apps.core.models
from django.db import migrations, models


def fill_time_from_created(apps, schema_editor):
    """Время уже существующих документов — момент их создания (местное время)."""
    from django.utils import timezone

    for name in ['Payment', 'AccountCorrection', 'SettlementCorrection']:
        model = apps.get_model('finance', name)
        for doc in model.objects.exclude(created_at=None).only("pk", "created_at"):
            local = timezone.localtime(doc.created_at).time().replace(microsecond=0)
            model.objects.filter(pk=doc.pk).update(time=local)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_accountcorrection_settlementcorrection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcorrection',
            options={'ordering': ['-date', '-time', '-id'], 'verbose_name': 'Корректировка остатка', 'verbose_name_plural': 'Корректировки остатков'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-time', '-id'], 'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='settlementcorrection',
            options={'ordering': ['-date', '-time', '-id'], 'verbose_name': 'Корректировка взаиморасчётов', 'verbose_name_plural': 'Корректировки взаиморасчётов'},
        ),
        migrations.AddField(
            model_name='accountcorrection',
            name='time',
            field=models.TimeField(default=apps.core.models.current_time, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='payment',
            name='time',
            field=models.TimeField(default=apps.core.models.current_time, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='settlementcorrection',
            name='time',
            field=models.TimeField(default=apps.core.models.current_time, verbose_name='Время'),
        ),
        migrations.RunPython(fill_time_from_created, migrations.RunPython.noop),
    ]
