# Generated by Django 6.0.7 on 2026-07-21 16:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Краткое наименование')),
                ('full_name', models.CharField(blank=True, max_length=512, verbose_name='Полное наименование')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН/ОГРНИП')),
                ('legal_address', models.CharField(blank=True, max_length=512, verbose_name='Юридический адрес')),
                ('actual_address', models.CharField(blank=True, max_length=512, verbose_name='Фактический адрес')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт')),
                ('corr_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт')),
                ('director_name', models.CharField(blank=True, max_length=255, verbose_name='Руководитель (ФИО)')),
                ('director_position', models.CharField(blank=True, default='Генеральный директор', max_length=255, verbose_name='Должность руководителя')),
                ('accountant_name', models.CharField(blank=True, max_length=255, verbose_name='Главный бухгалтер (ФИО)')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='org/', verbose_name='Подпись (картинка)')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='org/', verbose_name='Печать (картинка)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org/', verbose_name='Логотип')),
                ('vat_payer', models.BooleanField(default=True, verbose_name='Плательщик НДС')),
                ('is_default', models.BooleanField(default=False, verbose_name='Организация по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, max_length=512, verbose_name='Адрес')),
                ('is_default', models.BooleanField(default=False, verbose_name='Склад по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=32, verbose_name='Тип документа')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Последний номер')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'verbose_name': 'Нумератор документов',
                'verbose_name_plural': 'Нумераторы документов',
                'constraints': [models.UniqueConstraint(fields=('organization', 'doc_type', 'year'), name='uniq_doc_number')],
            },
        ),
    ]
