# Generated by Django 6.0.7 on 2026-08-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_negative_stock',
            field=models.BooleanField(default=False, verbose_name='Разрешить продажи в минус (без остатка)'),
        ),
    ]
