# Generated by Django 6.0.7 on 2026-08-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_allow_negative_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_vat_rate',
            field=models.CharField(choices=[('20', '20%'), ('10', '10%'), ('0', '0%'), ('none', 'Без НДС')], default='20', max_length=8, verbose_name='НДС по умолчанию'),
        ),
    ]
