# Generated by Django 6.0.7 on 2026-09-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_default_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('legal', 'Юридическое лицо'), ('entrepreneur', 'Индивидуальный предприниматель')], default='legal', max_length=16, verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='organization',
            name='signatory_basis',
            field=models.CharField(blank=True, default='Устава', help_text='Например: Устава, Свидетельства о регистрации, Доверенности № 5 от 01.01.2026', max_length=255, verbose_name='Действует на основании'),
        ),
    ]
