# Generated by Django 6.0.7 on 2026-09-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_kind_organization_signatory_basis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('url', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Токен отправки формы',
                'verbose_name_plural': 'Токены отправки форм',
            },
        ),
    ]
