# Generated by Django 6.0.7 on 2026-09-10 10:10

import apps.core.models
from django.db import migrations, models


def fill_time_from_created(apps, schema_editor):
    """Время уже существующих документов — момент их создания (местное время)."""
    from django.utils import timezone

    for name in ['Transfer', 'StockAdjustment']:
        model = apps.get_model('inventory', name)
        for doc in model.objects.exclude(created_at=None).only("pk", "created_at"):
            local = timezone.localtime(doc.created_at).time().replace(microsecond=0)
            model.objects.filter(pk=doc.pk).update(time=local)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockadjustment',
            options={'ordering': ['-date', '-time', '-id'], 'verbose_name': 'Оприходование/Списание', 'verbose_name_plural': 'Оприходования и списания'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-date', '-time', '-id'], 'verbose_name': 'Перемещение', 'verbose_name_plural': 'Перемещения'},
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='time',
            field=models.TimeField(default=apps.core.models.current_time, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='time',
            field=models.TimeField(default=apps.core.models.current_time, verbose_name='Время'),
        ),
        migrations.RunPython(fill_time_from_created, migrations.RunPython.noop),
    ]
