# Generated by Django 6.0.7 on 2026-09-10 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_track_serials'),
        ('core', '0005_submittoken'),
        ('inventory', '0002_alter_stockadjustment_options_alter_transfer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentline',
            name='serial_numbers',
            field=models.TextField(blank=True, help_text='По одному номеру в строке', verbose_name='Серийные номера'),
        ),
        migrations.AddField(
            model_name='transferline',
            name='serial_numbers',
            field=models.TextField(blank=True, help_text='По одному номеру в строке', verbose_name='Серийные номера'),
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=100, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('in_stock', 'На складе'), ('sold', 'Продан'), ('returned', 'Возвращён поставщику'), ('written_off', 'Списан')], default='in_stock', max_length=16, verbose_name='Состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='catalog.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='core.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Серийный номер',
                'verbose_name_plural': 'Серийные номера',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SerialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=32, verbose_name='Документ')),
                ('doc_id', models.PositiveIntegerField(verbose_name='ID документа')),
                ('doc_number', models.CharField(blank=True, max_length=32, verbose_name='Номер документа')),
                ('date', models.DateField(verbose_name='Дата документа')),
                ('quantity', models.SmallIntegerField(verbose_name='Приход (+1) / расход (−1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_movements', to='core.warehouse', verbose_name='Склад')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.serialnumber')),
            ],
            options={
                'verbose_name': 'Движение серийного номера',
                'verbose_name_plural': 'Движения серийных номеров',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='serialnumber',
            constraint=models.UniqueConstraint(fields=('product', 'number'), name='uniq_product_serial'),
        ),
        migrations.AddIndex(
            model_name='serialmovement',
            index=models.Index(fields=['doc_type', 'doc_id'], name='inventory_s_doc_typ_8a5c94_idx'),
        ),
    ]
