# Generated by Django 6.0.7 on 2026-07-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Обозначение')),
                ('okei_code', models.CharField(blank=True, max_length=8, verbose_name='Код ОКЕИ')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.productgroup', verbose_name='Родительская группа')),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Товар'), ('service', 'Услуга')], default='product', max_length=16, verbose_name='Тип')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('article', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Артикул')),
                ('code', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Код')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Штрихкод')),
                ('vat_rate', models.CharField(choices=[('20', '20%'), ('10', '10%'), ('0', '0%'), ('none', 'Без НДС')], default='20', max_length=8, verbose_name='Ставка НДС')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Закупочная цена')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена продажи')),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Неснижаемый остаток')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productgroup', verbose_name='Группа')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unit', verbose_name='Ед. изм.')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
