# Generated by Django 6.0.7 on 2026-09-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_serials',
            field=models.BooleanField(default=False, help_text='При приёмке, отгрузке и других складских операциях нужно указывать серийные номера', verbose_name='Учёт по серийным номерам'),
        ),
    ]
