# Generated by Django 6.0.7 on 2026-08-03 18:19

import apps.inventory.posting
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('partners', '0002_counterparty_okpo'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='Номер')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён')], default='draft', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Организация')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='purchases.receipt', verbose_name='Приёмка-основание')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns', to='partners.counterparty', verbose_name='Поставщик')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse', verbose_name='Со склада')),
            ],
            options={
                'verbose_name': 'Возврат поставщику',
                'verbose_name_plural': 'Возвраты поставщикам',
                'ordering': ['-date', '-id'],
            },
            bases=(apps.inventory.posting.PostableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SupplierReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=15, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('vat_rate', models.CharField(choices=[('20', '20%'), ('10', '10%'), ('0', '0%'), ('none', 'Без НДС')], default='20', max_length=8, verbose_name='Ставка НДС')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.supplierreturn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Строка возврата поставщику',
                'verbose_name_plural': 'Строки возврата поставщику',
            },
        ),
    ]
