# Generated by Django 6.0.7 on 2026-08-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_supplierreturn_supplierreturnline'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Скидка, %'),
        ),
        migrations.AddField(
            model_name='supplierreturnline',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Скидка, %'),
        ),
    ]
