# Generated by Django 6.0.7 on 2026-09-10 10:10

import apps.core.models
from django.db import migrations, models


def fill_time_from_created(apps, schema_editor):
    """Время уже существующих документов — момент их создания (местное время)."""
    from django.utils import timezone

    for name in ['Receipt', 'SupplierReturn']:
        model = apps.get_model('purchases', name)
        for doc in model.objects.exclude(created_at=None).only("pk", "created_at"):
            local = timezone.localtime(doc.created_at).time().replace(microsecond=0)
            model.objects.filter(pk=doc.pk).update(time=local)


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_receiptline_discount_supplierreturnline_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-date', '-time', '-id'], 'verbose_name': 'Приёмка', 'verbose_name_plural': 'Приёмки'},
        ),
        migrations.AlterModelOptions(
            name='supplierreturn',
            options={'ordering': ['-date', '-time', '-id'], 'verbose_name': 'Возврат поставщику', 'verbose_name_plural': 'Возвраты поставщикам'},
        ),
        migrations.AddField(
            model_name='receipt',
            name='time',
            field=models.TimeField(default=apps.core.models.current_time, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='time',
            field=models.TimeField(default=apps.core.models.current_time, verbose_name='Время'),
        ),
        migrations.RunPython(fill_time_from_created, migrations.RunPython.noop),
    ]
